[package]
name = "piston_start"
version = "0.1.0"
authors = ["bendou <sami.dahoux@etu.emse.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.98.0"
